Setup Rspec
CraftAcademy/cibus pull request #3
Opened 2018-07-09 18:34 UTC by ESteinman

### User story
```
As a development team,
In order to make unit testings
I would like to use Rspec as my Unit testing framework.
```
### What've learned
Change Ruby-version

2018-07-09 18:51 UTC, faraznaeem commented
- Missing PT link

2018-07-09 19:00 UTC, faraznaeem requested changes

2018-07-09 19:00 UTC, faraznaeem commented on spec/rails_helper.rb
> +Shoulda:Magchers.configure do |config|
Typo

2018-07-09 19:00 UTC, faraznaeem commented on spec/spec_helper.rb
> +end
clean comments

2018-07-09 19:17 UTC, ESteinman commented on spec/rails_helper.rb
> +Shoulda:Magchers.configure do |config|
Done

2018-07-09 19:17 UTC, ESteinman commented on spec/spec_helper.rb
> +end
Done

2018-07-10 07:42 UTC, faraznaeem approved these changes

2018-07-10 07:42 UTC, merged